dist: xenial
language: node_js
node_js:
  - "12"
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm install -g jshint
script:
  - jest --silent --coverage --coverageReporters=text-lcov && cat ./coverage/lcov.info | coveralls
  - jshint ./src
