dist: xenial
language: node_js
node_js:
  - "12"
cache:
  npm: true
  directories:
    - node_modules
addons:
  apt:
    packages:
      - graphviz
install:
  - npm install
  - npm install node-plantuml
before_script:
  - npm install -g jshint
script:
  - jest --silent --coverage --coverageReporters=text-lcov | coveralls
  - jshint ./src
