dist: xenial
language: node_js
node_js:
  - "10"
cache:
  npm: true
  directories:
    - node_modules
before_install:
  - chmod +x src/postinstall.js
install:
  - npm install
before_script:
  - npm install -g jshint
script:
  - npm test
  - jshint ./src
